"""Initial migration

Revision ID: 60869d6ea03a
Revises: 633ed8339fac
Create Date: 2025-08-24 20:25:30.589994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60869d6ea03a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('value', sa.Text(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('password', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('email', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('role', sa.Text(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('password', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container')
    op.drop_table('user')
    op.drop_table('Setting')
    # ### end Alembic commands ###
